---
# defaults file for allspark

allspark_root_domain: geekhomeinside.com
allspark_root_directory: /opt/geekhomeinside
allspark_backup_directory: /opt/geekhomeinside/backup
allspark_admin_user: admin

allspark_docker_version: "18.06.0"

allspark_monitoring:
  enabled: true

allspark_haproxy:
  ssl:
    enabled: true
    # If SSL is enabled, you can set the directory from which
    # endpoints certificates will be imported with this variable.
    # Files in the local directory should be PEM formatted certificates
    # named like their endpoint (e.g: `infra.allspark.localhost.pem`)
    certificates_directory:
    # If selfsigned certificates are enabled, any certificate missing
    # for an endpoint will be created on the fly.
    # If selfsigned is disabled and a certificate is missing, the
    # install won't be able to complete successfully.
    selfsigned:
      enabled: true
      # For example country: FR
      country: XX
      state: state
      location: city
      organisation: myteam
      organizational_unit: myorganizational_unit

allspark_backup:
  image: blacklabelops/volumerize

allspark_mattermost:
  enabled: false

allspark_portainer:
  enabled: true

allspark_web:
  enabled: false

allspark_intranet:
  enabled: false

allspark_kodidb:
  enabled: true

allspark_keepass:
  enabled: false
