stages:
  # - test
  # - storekey
  - validate
  - plan
  - apply
  - destroy

# variables:
#   COMMIT_AUTHOR_EMAIL: "guiadco@geekhomeinside.com"
#
# build-docs:
#   stage: test
#   image: python:latest
#   script:
#     - pip install --user virtualenv
#     - chmod +x .gitlabci/deploy-ghpages.sh
#     - PATH=$PATH:/root/.local/bin .gitlabci/deploy-ghpages.sh docs
#   only:
#     - master
#
# ansible-lint:
#   stage: test
#   image: python:latest
#   script:
#     - chmod +x ./.gitlabci/lint.sh
#     - ./.gitlabci/lint.sh

before_script:
    # - git clone https://github.com/actiniumio/terraform-gcp-europe.git ${HOME}/terraform
    - echo $GCLOUD_SERVICE_KEY > ./account.json
    - terraform init

validate:
  stage: validate
  script:
    - terraform validate -var 'project-name=$GCP_PROJECT_ID' -var 'vmcount=1' -var 'region=europe-west1-b' -var 'instance-name=allspark' -var 'subnetwork-region=europe-west1' -var 'network=allspark-network' -var 'vm_type=n1-standard-2' -var 'os=centos-7-v20180815' -out "planfile"

terraform-plan:
  stage: plan
  image: hashicorp/terraform:full
  script:
    - terraform plan -var 'project-name=$GCP_PROJECT_ID' -var 'vmcount=1' -var 'region=europe-west1-b' -var 'instance-name=allspark' -var 'subnetwork-region=europe-west1' -var 'network=allspark-network' -var 'vm_type=n1-standard-2' -var 'os=centos-7-v20180815' -out "planfile"
  cache:
    paths:
      - planfile
      - *.tfstate

terraform-apply:
  stage: apply
  image: hashicorp/terraform:full
  script:
    - terraform apply -var 'project-name=$GCP_PROJECT_ID' -var 'vmcount=1' -var 'region=europe-west1-b' -var 'instance-name=allspark' -var 'subnetwork-region=europe-west1' -var 'network=allspark-network' -var 'vm_type=n1-standard-2' -var 'os=centos-7-v20180815' -auto-approve
  cache:
    paths:
      - planfile
      - *.tfstate
  dependencies:
    - terraform-plan

terraform-destroy:
  stage: destroy
  image: hashicorp/terraform:full
  script:
    - terraform destroy -var 'project-name=$GCP_PROJECT_ID' -var 'vmcount=1' -var 'region=europe-west1-b' -var 'instance-name=allspark' -var 'subnetwork-region=europe-west1' -var 'network=allspark-network' -var 'vm_type=n1-standard-2' -var 'os=centos-7-v20180815' -auto-approve
  dependencies:
    - terraform-apply
