image: python:3.7.1

variables:
  COMMIT_AUTHOR_EMAIL: "guiadco@geekhomeinside.com"

build-docs:
  script:
  - pip install --user virtualenv
  - chmod +x .circleci/deploy-ghpages.sh
  - PATH=$PATH:/root/.local/bin .circleci/deploy-ghpages.sh docs
  only:
  - master
