stages:
  # - test
  # - storekey
  - plan
  - apply
  - destroy

# variables:
#   COMMIT_AUTHOR_EMAIL: "guiadco@geekhomeinside.com"
#
# build-docs:
#   stage: test
#   image: python:latest
#   script:
#     - pip install --user virtualenv
#     - chmod +x .circleci/deploy-ghpages.sh
#     - PATH=$PATH:/root/.local/bin .circleci/deploy-ghpages.sh docs
#   only:
#     - master
#
# ansible-lint:
#   stage: test
#   image: python:latest
#   script:
#     - chmod +x ./.circleci/lint.sh
#     - ./.circleci/lint.sh

before_script:
    # - git clone https://github.com/actiniumio/terraform-gcp-europe.git ${HOME}/terraform
    - touch ${HOME}/terraform/account.json
    - echo $GCLOUD_SERVICE_KEY > ${HOME}/terraform/account.json
    - terraform init ${HOME}/terraform

terraform-plan:
  stage: plan
  image: hashicorp/terraform:light
  script:
    - terraform plan -var 'project-name=$GCP_PROJECT_ID' -var 'vmcount=1' -var 'region=europe-west1-b' -var 'instance-name=allspark' -var 'subnetwork-region=europe-west1' -var 'network=allspark-network' -var 'vm_type=n1-standard-2' -var 'os=centos-7-v20180815' -out "planfile" ${HOME}/terraform
  cache:
    paths:
      - ${HOME}/terraform/
      - planfile

terraform-apply:
  stage: apply
  image: hashicorp/terraform:light
  script:
    - terraform apply -var 'project-name=$GCP_PROJECT_ID' -var 'vmcount=1' -var 'region=europe-west1-b' -var 'instance-name=allspark' -var 'subnetwork-region=europe-west1' -var 'network=allspark-network' -var 'vm_type=n1-standard-2' -var 'os=centos-7-v20180815' -auto-approve ${HOME}/terraform
  cache:
    paths:
      - ${HOME}/terraform/
      - planfile
  dependencies:
    - terraform-plan

terraform-destroy:
  stage: destroy
  image: hashicorp/terraform:light
  script:
    - terraform destroy -var 'project-name=$GCP_PROJECT_ID' -var 'vmcount=1' -var 'region=europe-west1-b' -var 'instance-name=allspark' -var 'subnetwork-region=europe-west1' -var 'network=allspark-network' -var 'vm_type=n1-standard-2' -var 'os=centos-7-v20180815' -auto-approve ${HOME}/terraform
  dependencies:
    - terraform-apply
