stages:
  # - test
  - validate-plan-apply
  - destroy

# variables:
#   COMMIT_AUTHOR_EMAIL: "guiadco@geekhomeinside.com"
#
# build-docs:
#   stage: test
#   image: python:latest
#   script:
#     - pip install --user virtualenv
#     - chmod +x .gitlabci/deploy-ghpages.sh
#     - PATH=$PATH:/root/.local/bin .gitlabci/deploy-ghpages.sh docs
#   only:
#     - master
#
# ansible-lint:
#   stage: test
#   image: python:latest
#   script:
#     - chmod +x ./.gitlabci/lint.sh
#     - ./.gitlabci/lint.sh

terraform-validate-plan-apply:
  stage: validate-plan-apply
  image:
    name: hashicorp/terraform:light
    entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    - git clone https://github.com/actiniumio/terraform-gcp-europe.git
    - cd terraform-gcp-europe
    - ls -ltr
    - pwd
    - echo $GCLOUD_SERVICE_KEY > ./account.json
    - ls -ltr
    - terraform init
    - terraform validate -var "project-name=$GCP_PROJECT_ID" -var 'vmcount=1' -var 'region=europe-west1-b' -var 'instance-name=allspark' -var 'subnetwork-region=europe-west1' -var 'network=allspark-network' -var 'vm_type=n1-standard-2' -var 'os=centos-7-v20180815'
    - terraform plan -var "project-name=$GCP_PROJECT_ID" -var 'vmcount=1' -var 'region=europe-west1-b' -var 'instance-name=allspark' -var 'subnetwork-region=europe-west1' -var 'network=allspark-network' -var 'vm_type=n1-standard-2' -var 'os=centos-7-v20180815' -out "planfile"
    - terraform apply -var "project-name=$GCP_PROJECT_ID" -var 'vmcount=1' -var 'region=europe-west1-b' -var 'instance-name=allspark' -var 'subnetwork-region=europe-west1' -var 'network=allspark-network' -var 'vm_type=n1-standard-2' -var 'os=centos-7-v20180815' -auto-approve
  cache:
    paths:
      - terraform-gcp-europe/

terraform-destroy:
  stage: destroy
  image:
    name: hashicorp/terraform:light
    entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    - ls -ltr
    - pwd
    - cd terraform-gcp-europe
    - ls -ltr
    - pwd
    - terraform destroy -var "project-name=$GCP_PROJECT_ID" -var 'vmcount=1' -var 'region=europe-west1-b' -var 'instance-name=allspark' -var 'subnetwork-region=europe-west1' -var 'network=allspark-network' -var 'vm_type=n1-standard-2' -var 'os=centos-7-v20180815' -auto-approve
  cache:
    paths:
      - terraform-gcp-europe/
  dependencies:
    - terraform-validate-plan-apply
