stages:
  - test
  - validate-plan-apply
  - test install on centos 7
  - destroy

# variables:
#   COMMIT_AUTHOR_EMAIL: "guiadco@geekhomeinside.com"
#
# github_pages:
#   image: andthensome/alpine-hugo-git-bash:0.31.2
#   script:
#   - rm -rf public
#   - git clone --depth 1 https://actiniumio:$GITHUB_ACCESS_TOKEN@github.com/<username>/<username>.github.io.git public
#   - hugo --config config.production.toml
#   - cd public
#   - git config user.email "<your git email>"
#   - git config --global user.name "<your git name>"
#   - git add -A
#   - git commit -m "Build from $CI_SERVER_NAME $CI_PIPELINE_ID"
#   - git push
# build-docs:
#   stage: test
#   image: python:latest
#   script:
#     - pip install --user virtualenv
#     - chmod +x .gitlabci/deploy-ghpages.sh
#     - PATH=$PATH:/root/.local/bin .gitlabci/deploy-ghpages.sh docs
#   only:
#     - master

ansible-lint:
  stage: test
  image: python:latest
  script:
    - chmod +x ./.gitlabci/lint.sh
    - ./.gitlabci/lint.sh

terraform-validate-plan-apply:
  stage: validate-plan-apply
  image:
    name: hashicorp/terraform:light
    entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    - git clone https://github.com/actiniumio/terraform-gcp-europe.git
    - cd terraform-gcp-europe
    - echo $GCLOUD_SERVICE_KEY > ./account.json
    - terraform init
    - terraform validate -var "project-name=$GCP_PROJECT_ID" -var 'vmcount=1' -var 'region=europe-west1-b' -var 'instance-name=allspark-centos7' -var 'subnetwork-region=europe-west1' -var 'network=allspark-network' -var 'vm_type=n1-standard-2' -var 'os=centos-7-v20180815'
    - terraform plan -var "project-name=$GCP_PROJECT_ID" -var 'vmcount=1' -var 'region=europe-west1-b' -var 'instance-name=allspark-centos7' -var 'subnetwork-region=europe-west1' -var 'network=allspark-network' -var 'vm_type=n1-standard-2' -var 'os=centos-7-v20180815' -out "planfile"
    - terraform apply -var "project-name=$GCP_PROJECT_ID" -var 'vmcount=1' -var 'region=europe-west1-b' -var 'instance-name=allspark-centos7' -var 'subnetwork-region=europe-west1' -var 'network=allspark-network' -var 'vm_type=n1-standard-2' -var 'os=centos-7-v20180815' -auto-approve
  cache:
    key: "TERRAFORM-CENTOS7-$CI_PIPELINE_ID"
    paths:
      - terraform-gcp-europe/

gcp-test-allspark-centos7:
  stage: test install on centos 7
  image:
    name: google/cloud-sdk:latest
    entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    - echo $GCLOUD_SERVICE_KEY > ./account.json
    - gcloud auth activate-service-account --key-file=./account.json
    - gcloud --quiet config set project $GCP_PROJECT_ID
    - gcloud --quiet config set compute/zone $GCP_PROJECT_ZONE
    - gcloud compute --quiet scp --recurse . bot_actinium@allspark-centos7-1:~/ --zone "$GCP_PROJECT_ZONE"
    - gcloud compute --quiet --project "$GCP_PROJECT_ID" ssh --zone "$GCP_PROJECT_ZONE" bot_actinium@allspark-centos7-1 -- 'sudo yum -y install ansible'
    - gcloud compute --quiet --project "$GCP_PROJECT_ID" ssh --zone "$GCP_PROJECT_ZONE" bot_actinium@allspark-centos7-1 -- 'sudo ansible-playbook -i .gitlabci/hosts.gitlabci install.yml'
    - gcloud compute --quiet --project "$GCP_PROJECT_ID" ssh --zone "$GCP_PROJECT_ZONE" bot_actinium@allspark-centos7-1 -- 'docker ps -a'
    - gcloud compute --quiet --project "$GCP_PROJECT_ID" ssh --zone "$GCP_PROJECT_ZONE" bot_actinium@allspark-centos7-1 -- 'docker volume ls'
    - gcloud compute --quiet --project "$GCP_PROJECT_ID" ssh --zone "$GCP_PROJECT_ZONE" bot_actinium@allspark-centos7-1 -- 'ls -Rltr /opt/allspark'
    - gcloud compute --quiet --project "$GCP_PROJECT_ID" ssh --zone "$GCP_PROJECT_ZONE" bot_actinium@allspark-centos7-1 -- 'chmod +x .gitlabci/security-bench.sh'
    - gcloud compute --quiet --project "$GCP_PROJECT_ID" ssh --zone "$GCP_PROJECT_ZONE" bot_actinium@allspark-centos7-1 -- '.gitlabci/security-bench.sh'
  dependencies:
    - terraform-validate-plan-apply

terraform-destroy:
  stage: destroy
  image:
    name: hashicorp/terraform:light
    entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    - cd terraform-gcp-europe
    - terraform destroy -var "project-name=$GCP_PROJECT_ID" -var 'vmcount=1' -var 'region=europe-west1-b' -var 'instance-name=allspark-centos7' -var 'subnetwork-region=europe-west1' -var 'network=allspark-network' -var 'vm_type=n1-standard-2' -var 'os=centos-7-v20180815' -auto-approve
  cache:
    key: "TERRAFORM-CENTOS7-$CI_PIPELINE_ID"
    paths:
      - terraform-gcp-europe/
  dependencies:
    - gcp-test-allspark-centos7
