stages:
  - test
  - provision
  - destroy

image: python:3.7.1

variables:
  COMMIT_AUTHOR_EMAIL: "guiadco@geekhomeinside.com"

build-docs:
  stage: test
  script:
  - pip install --user virtualenv
  - chmod +x .circleci/deploy-ghpages.sh
  - PATH=$PATH:/root/.local/bin .circleci/deploy-ghpages.sh docs
  only:
  - master

image: python:3.7.1

ansible-lint:
  stage: test
  script:
    - chmod +x ./.circleci/lint.sh
    - ./.circleci/lint.sh

image: terraform:latest

terraform-provision:
  stage: provision
  script:
      - git clone https://github.com/actiniumio/terraform-gcp-europe.git ~/terraform
      - touch ${HOME}/terraform/account.json
      - echo $GCLOUD_SERVICE_KEY > ${HOME}/terraform/account.json
      - terraform init
      - terraform validate -var 'project-name=$GCP_PROJECT_ID' -var 'vmcount=1' -var 'region=europe-west1-b' -var 'instance-name=allspark' -var 'subnetwork-region=europe-west1' -var 'network=allspark-network' -var 'vm_type=n1-standard-2' -var 'os=centos-7-v20180815'
      - terraform plan -var 'project-name=$GCP_PROJECT_ID' -var 'vmcount=1' -var 'region=europe-west1-b' -var 'instance-name=allspark' -var 'subnetwork-region=europe-west1' -var 'network=allspark-network' -var 'vm_type=n1-standard-2' -var 'os=centos-7-v20180815'
      - terraform apply -var 'project-name=$GCP_PROJECT_ID' -var 'vmcount=1' -var 'region=europe-west1-b' -var 'instance-name=allspark' -var 'subnetwork-region=europe-west1' -var 'network=allspark-network' -var 'vm_type=n1-standard-2' -var 'os=centos-7-v20180815' -auto-approve
  artifacts:
    paths:
      - ~/terraform

image: circleci/terraform:0.11.8

terraform-destroy:
  stage: destroy
  script:
    - terraform destroy -var 'project-name=$GCP_PROJECT_ID' -var 'vmcount=1' -var 'region=europe-west1-b' -var 'instance-name=allspark' -var 'subnetwork-region=europe-west1' -var 'network=allspark-network' -var 'vm_type=n1-standard-2' -var 'os=centos-7-v20180815' -auto-approve
  dependencies:
    - terraform-provision
