stages:
  # - test
  # - storekey
  - validate
  - plan
  - apply
  - destroy

# variables:
#   COMMIT_AUTHOR_EMAIL: "guiadco@geekhomeinside.com"
#
# build-docs:
#   stage: test
#   image: python:latest
#   script:
#     - pip install --user virtualenv
#     - chmod +x .gitlabci/deploy-ghpages.sh
#     - PATH=$PATH:/root/.local/bin .gitlabci/deploy-ghpages.sh docs
#   only:
#     - master
#
# ansible-lint:
#   stage: test
#   image: python:latest
#   script:
#     - chmod +x ./.gitlabci/lint.sh
#     - ./.gitlabci/lint.sh

before_script:
    - git clone https://github.com/actiniumio/terraform-gcp-europe.git ~/terraform
    - cd ~/terraform
    - ls -ltr
    - pwd
    - echo $GCLOUD_SERVICE_KEY > ./account.json
    - ls -ltr
    - terraform init

terraform-validate:
  stage: validate
  image:
    name: hashicorp/terraform:light
    entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    - terraform validate -var 'project-name=corded-skill-214716' -var 'vmcount=1' -var 'region=europe-west1-b' -var 'instance-name=allspark' -var 'subnetwork-region=europe-west1' -var 'network=allspark-network' -var 'vm_type=n1-standard-2' -var 'os=centos-7-v20180815'

terraform-plan:
  stage: plan
  image:
    name: hashicorp/terraform:light
    entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    - terraform plan -var 'project-name=corded-skill-214716' -var 'vmcount=1' -var 'region=europe-west1-b' -var 'instance-name=allspark' -var 'subnetwork-region=europe-west1' -var 'network=allspark-network' -var 'vm_type=n1-standard-2' -var 'os=centos-7-v20180815' -out "planfile"
    - ls -ltr
    - pwd
  cache:
    paths:
      - planfile
  dependencies:
    - terraform-validate

terraform-apply:
  stage: apply
  image:
    name: hashicorp/terraform:light
    entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    - terraform apply -var "project-name=$GCP_PROJECT_ID" -var 'vmcount=1' -var 'region=europe-west1-b' -var 'instance-name=allspark' -var 'subnetwork-region=europe-west1' -var 'network=allspark-network' -var 'vm_type=n1-standard-2' -var 'os=centos-7-v20180815' -auto-approve
    - ls -ltr
    - pwd
  cache:
    paths:
      - terraform.tfstate
  dependencies:
    - terraform-plan

terraform-destroy:
  stage: destroy
  image:
    name: hashicorp/terraform:light
    entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    - terraform destroy -var "project-name=$GCP_PROJECT_ID" -var 'vmcount=1' -var 'region=europe-west1-b' -var 'instance-name=allspark' -var 'subnetwork-region=europe-west1' -var 'network=allspark-network' -var 'vm_type=n1-standard-2' -var 'os=centos-7-v20180815' -auto-approve
  dependencies:
    - terraform-apply
