- name: GeekHomeInside installer
  hosts: all
  roles:
    - system
    - pip
    - { role: download, tags: [ "download", "prepare" ] }
    - local_datas
    - network
    - haproxy
    - ldap
    - utils
    - monitoring
    - gitlab
    - jenkins
    - sonarqube
    - web
    - intranet
    - keepass
    - kodidb
