version: 2
jobs:
  build-docs:
    docker:
      - image: circleci/python:3.6.3
    environment:
      - COMMIT_AUTHOR_EMAIL: "guiadco4geekhomeinside@gmail.com"
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "6f:9b:63:ef:04:14:96:51:f1:c2:4f:d4:f5:7a:77:dd"
      - run:
          name: Install Virtualenv dependencies for Pip
          command: pip install --user virtualenv
      - run:
          name: Prepare shell commands
          command: chmod +x .circleci/deploy-ghpages.sh
      - deploy:
          name: Deploy
          command: PATH=$PATH:/home/circleci/.local/bin/ .circleci/deploy-ghpages.sh docs
  test-ansible-lint:
    docker:
      - image: python:2.7
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "6f:9b:63:ef:04:14:96:51:f1:c2:4f:d4:f5:7a:77:dd"
      - run: pip install --user -r ./.circleci/requirements.txt
      - run: PATH=$PATH:/root/.local/bin ansible-lint ./playbooks/*.yml -c .circleci/.ansible-lint
      - run: PATH=$PATH:/root/.local/bin ansible-lint ./roles/**/**/*.yml -c .circleci/.ansible-lint
  test-playbook-install:
    machine: true
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6f:9b:63:ef:04:14:96:51:f1:c2:4f:d4:f5:7a:77:dd"
      - run: sudo apt-get update -y
      - run: sudo apt-add-repository ppa:ansible/ansible
      - run: sudo apt-get update -y
      - run: git clone https://github.com/guiadco/geekhomeinside.git ~/repo
      - run: pip install --upgrade pip
      - run: pip install --user ansible==2.5.5
#      - run: sudo apt-get install -y ansible
      - run: sudo find / -name "*ansible*" || true
      - run: sudo find / -name "*pip*" || true
      - run: pip freeze | grep -i ansible || true
      - run: sudo cp /home/circleci/repo/.circleci/ansible.cfg /etc/ansible/ansible.cfg
      - run: sudo cp /home/circleci/repo/.circleci/testall.yml /home/circleci/repo/group_vars/all.yml
      - run: sudo PATH=$PATH:/root/.local/bin ansible-playbook -i hosts playbooks/install.yml -vvv
      - run: pip --version
      - run: pip freeze
      - run: sudo docker ps -a
      - run: sudo docker volume ls

workflows:
  version: 2
  test-to-master:
    jobs:
      - test-ansible-lint
      - build-docs
      - test-playbook-install
