- name: read vars from first file found, use 'vars/' relative subdir
  include_vars: "{{ item }}"
  with_first_found: "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
  tags: vars

- name: Docker - Ensuring daemon is started
  systemd: state=started name=docker
  become: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: FS - Ensuring Allspark directory
  file:
    path: "{{ allspark_root_directory }}"
    state: "directory"
  become: true

- name: FS - Ensuring Allspark directory owner
  file:
    path: "{{ allspark_root_directory }}"
    owner: "{{ ansible_user }}"
  become: true
