---


- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  become: yes

# Normaly linux-image-extra-4.4.0-96-generic
- name: Install [linux-image-extra-$(uname -r)]
  apt:
    name: linux-image-extra-$(uname -r)
  become: yes

- name: Install [linux-image-extra-virtual]
  apt:
    name: linux-image-extra-virtual
  become: yes

- name: Install [apt-transport-https]
  apt:
    name: apt-transport-https
  become: yes

- name: Install [ca-certificates]
  apt:
    name: ca-certificates
  become: yes

- name: Install [curl]
  apt:
    name: curl
  become: yes

- name: Install [software-properties-common]
  apt:
    name: software-properties-common
  become: yes

- name: Add Docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  ignore_errors: true

- name: [Docker] Add repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
    state: present
  become: yes

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: [Docker] Ensure old versions of Docker are not installed
  apt:
    name: '{{ packages }}'
    state: absent
  packages:
    - docker
    - docker.io
    - docker-engine
  when: ansible_os_family == 'Ubuntu'
  become: yes

- name: test [pip] install
  shell: which pip
  failed_when: false
  changed_when: false
  register: pip_install
  #Will be fix with issue #73
  tags:
  - skip_ansible_lint

- name: Install [Python-pip]
  apt:
    name: python-pip
  become: yes
  when: pip_install.rc != 0

- name: test docker install
  shell: which docker
  changed_when: false
  failed_when: false
  register: docker_install
  #Will be fix with issue #73
  tags:
  - skip_ansible_lint

- name: Install [Docker]
  apt:
    pkg: docker-ce
    update_cache: yes
  become: yes
  when: docker_install.rc != 0

- name: Start Docker service
  service:
    name: docker
    state: restarted
    enabled: yes
  become: yes

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  become: yes
  register: user_task

# - name: Reset ssh connection
#   meta: reset_connection
#   when: user_task is changed
#   failed_when: false

# Below is an ugly hack, because of an issue with
# `meta: reset_connection`:
## ERROR! Cannot reset connection
## b'Control socket connect(/home/$USER/.ansible/cp/276d6f8b70): No such file or directory\r\n'
#
# So we use this trick to force ansible to reconnect
- name: Remove cp dir to force ssh reconnection.
  file:
    path: ~/.ansible/cp
    state: absent
  delegate_to: localhost
  changed_when: false
  when: user_task is changed

