- name: Docker volumes creation for Frontal Web Server
  docker_volume:
    name: "allspark_logs_data"

- name: Setup Web WWW as Frontal Web Server service
  docker_container:
    name: geekhomeinside
    image: "{{ allspark_www.image }}"
    volumes:
      - "/var/www/html:/var/www/html"
      - "allspark_logs_data:/var/log/apache2"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - name: allspark
    labels:
      "traefik.backend": "www"
      "traefik.frontend.rule": "Host:{{ allspark_root_domain }}"
      "traefik.enable": "true"
    restart_policy: always
